CREATE DATABASE hojetemfesta;
USE hojetemfesta;

CREATE TABLE membro (
  id INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  nome VARCHAR(255)  NULL,
  apelido VARCHAR(255)  NULL,
  sobrenomes VARCHAR(255)  NULL,
  cargo VARCHAR(255)  NULL,
  dia INTEGER UNSIGNED  NOT NULL,
  mes INTEGER UNSIGNED  NOT NULL,
  ano INTEGER UNSIGNED  NOT NULL,
PRIMARY KEY(id));
